version: '3'
services:
  arima:
    image: arima_image
    volumes:
      - ./config.properties:/ArimaModule_latest/config.properties
    environment:
      - FILE_PATH=/ArimaModule_latest/config.properties
      - ARIMA_PATH=/ArimaModule_latest/ARIMA
    networks:
      - arimaNetwork
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
#    environment:
#      - MONGO_INITDB_ROOT_USERNAME=mongo
#      - MONGO_INITDB_ROOT_PASSWORD=mongo
    ports:
      - "27017:27017"
    networks:
      - arimaNetwork
    command: mongod --bind_ip_all

  portainer:
    image: portainer/portainer-ce
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - arimaNetwork

networks:
  arimaNetwork:
    driver: bridge
